# Generated by Django 4.2.5 on 2023-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0002_csvfiles_csvcolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='file_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
