# Generated by Django 4.2.5 on 2023-09-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0004_csvfiles_file_column_name_delete_csvcolumns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_data', models.CharField(max_length=255)),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task_app.csvfiles')),
            ],
        ),
    ]
