# Generated by Django 4.2.5 on 2023-09-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0005_csvdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
