# Generated by Django 4.2.5 on 2023-09-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_app', '0007_columndata_delete_csvdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfiles',
            name='file_column_name',
        ),
    ]
